add poetry support

diff --git a/.github/workflows/python-egg.yml b/.github/workflows/python-egg.yml
--- a/.github/workflows/python-egg.yml
+++ b/.github/workflows/python-egg.yml
@@ -15,26 +15,40 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        python-version: [3.7, 3.8]
-        os: [ubuntu-20.04, macOS-latest]
+        python-version: [3.9, 3.8]
+        os: [ubuntu-latest, macOS-latest]
     steps:
     - uses: actions/checkout@v2
       with:
         ref: ${{ github.ref }}
+
     - name: Setup Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Set up Dist Environment
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install wheel setuptools
+
+    - uses: abatilo/actions-poetry@v2.1.4
+
     - name: Install Application and Plugins
       run: |
-        make clean build
+        poetry install -vvv
+
     - name: Package Application and Plugins
       run: |
-        make clean dist
+        poetry run "make" "build"
+
+    - name: Run Format Check
+      run: |
+        # poerty run "make" "format"
+        # Note: black fails when it doesn't have to do anything.
+        git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/master HEAD) |
+          grep -v '.json$' |
+          2>/dev/null xargs black || true
+        git diff --exit-code
+
+    - name: Run flake8 lint Check
+      run: |
+        # poetry run "make" "lint"
 
   test:
     name: Unit Tests
@@ -44,24 +58,29 @@ jobs:
     - uses: actions/checkout@v2
       with:
         ref: ${{ github.ref }}
+
     - name: Set up Dist Environment
       run: |
         apt-get -qq update
-        apt-get -qqy install python3-pip software-properties-common gnupg2 libbroker2 python3-broker
+        apt-get -qqy install python3-pip libbroker2 python3-broker
         update-alternatives --install /usr/bin/python python /usr/bin/python3 1
         python -m pip install --upgrade pip
-        python -m pip install wheel setuptools
+        python -m pip install poetry
+        python -c 'import broker; print(broker.__file__)'
+
     - name: Install Application and Plugins
-      run: |
-        make dev-mode
+      run: poetry install -vvv
+
+    - name: Install Zeek Broker to Poetry
+      run: poetry run "bash" "./plugins/apps/threatbus_zeek/install_broker.bash"
+
     - name: Run Unit Tests
-      run: |
-        make unit-tests
+      run: poetry run "make" "unit-tests"
 
   docker-release:
     name: Publish to DockerHub
     if: ${{ github.event_name == 'release' || github.event_name == 'push' }}
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     needs: egg-install
     steps:
     - uses: actions/checkout@v2
@@ -103,7 +122,7 @@ jobs:
     name: Egg Release
     if: github.event_name == 'release'
     needs: egg-install
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     env:
       TWINE_USERNAME: __token__
       TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
@@ -112,29 +131,16 @@ jobs:
       with:
         ref: ${{ github.ref }}
     - name: Set up Python 3.8
-      uses: actions/setup-python@v1
+      uses: actions/setup-python@v2
       with:
         python-version: 3.8
-    - name: Set up Dist Environment
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install wheel setuptools twine
+
+    - uses: abatilo/actions-poetry@v2.1.4
+
     - name: Package Application and Plugins
       run: |
-        make clean dist
-    - name: Create Release
-      id: create_release
-      run: |
-        NAME="Threat Bus $(date +%Y-%m-%d)"
-        ARCHIVE="$NAME.tar"
-        tar cf "$ARCHIVE" apps/zeek
-        find -type d -name dist -exec tar uvf "$ARCHIVE" {} \;
-        gzip "$ARCHIVE"
-        ASSET="$ARCHIVE.gz"
-        echo "::set-output name=name::$NAME"
-        echo "::set-output name=asset::$ASSET"
-    # This step ensures that assets from previous runs are cleaned up to avoid
-    # failure of the next step (asset upload)
+        poetry run "make" "build"
+
     - name: Delete existing Release Assets
       uses: mknejp/delete-release-assets@v1
       with:
